name: Terraform CI (Build Once)

on:
  pull_request:
    branches:
      - main
    paths:
      - "OVING2/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-artifact:
    name: Validate & Build Artifact
    runs-on: ubuntu-latest
    env:
      WORKDIR: "OVING2/terraform"
      BACKEND_HCL: "OVING2/shared/backend.hcl"
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
      KEYVAULT_NAME: "kv-tfstate-jfk"

    outputs:
      artifact_name: ${{ steps.build.outputs.artifact_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"

      - name: Terraform Format Check
        working-directory: ${{ env.WORKDIR }}
        run: terraform fmt -check -recursive

      - name: Terraform Init (no backend)
        working-directory: ${{ env.WORKDIR }}
        run: terraform init -backend=false -input=false -no-color

      - name: Terraform Validate
        working-directory: ${{ env.WORKDIR }}
        run: terraform validate -no-color

      - name: Build Terraform Artifact
        id: build
        run: |
          VERSION=$(git rev-parse --short HEAD || date +%Y%m%d-%H%M%S)
          ARTIFACT_NAME="terraform-${VERSION}.tar.gz"
          tar -czf "$ARTIFACT_NAME" OVING2/
          echo "artifact_name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifact
          path: ${{ steps.build.outputs.artifact_name }}

  plan-all-environments:
    name: Terraform Plan - ${{ matrix.environment }}
    runs-on: ubuntu-latest
    needs: build-artifact
    strategy:
      matrix:
        environment: [dev, test, prod]

    env:
      WORKDIR: "OVING2/terraform"
      BACKEND_HCL: "OVING2/shared/backend.hcl"
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
      KEYVAULT_NAME: "kv-tfstate-jfk"

    steps:
      - name: Download Terraform Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-artifact

      - name: Extract Artifact
        run: tar -xzf terraform-*.tar.gz

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"

      - name: Fetch tfvars from Azure Key Vault
        run: |
          echo "Fetching tfvars for ${{ matrix.environment }}..."
          mkdir -p "${{ env.WORKDIR }}"
          SECRET_B64=$(az keyvault secret show \
            --vault-name ${{ env.KEYVAULT_NAME }} \
            --name "${{ matrix.environment }}-tfvars-oblig2" \
            --query value -o tsv)
          echo "$SECRET_B64" | base64 -d > "${{ env.WORKDIR }}/${{ matrix.environment }}.tfvars"
          echo "✅ Decoded and saved ${{ matrix.environment }}.tfvars"

      - name: Terraform Init
        working-directory: ${{ env.WORKDIR }}
        run: |
          terraform init \
            -backend-config="${{ github.workspace }}/${{ env.BACKEND_HCL }}" \
            -backend-config="key=projects/storageaccount/${{ matrix.environment }}/${{ matrix.environment }}.tfstate" \
            -input=false \
            -no-color

      - name: Terraform Plan
        working-directory: ${{ env.WORKDIR }}
        id: plan
        run: |
          set +e
          terraform plan -no-color \
            -var-file="${{ matrix.environment }}.tfvars" \
            -out="${{ matrix.environment }}.tfplan" 2>&1 | tee plan-output.txt
          PLAN_EXIT_CODE=${PIPESTATUS[0]}
          set -e

          {
            echo "PLAN_EXIT_CODE=${PLAN_EXIT_CODE}"
            echo 'PLAN_OUTPUT<<EOF'
            cat plan-output.txt
            echo 'EOF'
          } >> "$GITHUB_ENV"
          exit ${PLAN_EXIT_CODE}
        continue-on-error: true

      - name: Comment PR with Plan
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const planOutput = process.env.PLAN_OUTPUT || 'No plan output available';
            const exitCode = process.env.PLAN_EXIT_CODE || 'unknown';
            const status = (exitCode === '0' || exitCode === '2') ? '✅ Success' : '❌ Failed';
            const output = `#### Terraform Plan for \`${{ matrix.environment }}\` 📋 ${status}

            <details><summary>Show Plan</summary>

            \`\`\`terraform
            ${planOutput}
            \`\`\`

            </details>

            **Exit Code:** ${exitCode}

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
